### ISSUE TITLE
Working kubernetes manifest

### ISSUE THREAD

**Issue by alexgorbatchev** [Quiq/registry-ui#53]
Posting this for those that will be looking for something like this. I have a working kubernetes manifest that works with cert-manger and traefik.

Please note to update `container/image` and `config.yml` as appropriate. Hope this helps.

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-ui
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      name: docker-registry-ui
  template:
    metadata:
      labels:
        name: docker-registry-ui
    spec:
      containers:
        - name: docker-registry-ui
          image: docker-registry.local/cluster/docker-registry-ui
          args:
            - -config-file=/var/docker-registry-ui/config.yml
          resources: {}
          env:
            - name: TZ
              value: America/Los_Angeles
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /opt/data
              name: data
            - mountPath: /var/docker-registry-ui
              name: config
      volumes:
        - name: config
          configMap:
            name: docker-registry-ui-config
        - name: data
          persistentVolumeClaim:
            claimName: docker-registry-ui-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-ui-config
  namespace: docker-registry
data:
  config.yml: |-
    # Listen interface.
    listen_addr: 0.0.0.0:8000
    # Base path of Docker Registry UI.
    base_path: /ui

    # Registry URL with schema and port.
    registry_url: https://docker-registry.local
    # Verify TLS certificate when using https.
    verify_tls: true

    # Docker registry credentials.
    # They need to have a full access to the registry.
    # If token authentication service is enabled, it will be auto-discovered and those credentials
    # will be used to obtain access tokens.
    # When the registry_password_file entry is used, the password can be passed as a docker secret
    # and read from file. This overides the registry_password entry.
    # registry_username: user
    # registry_password: pass
    # registry_password_file: /run/secrets/registry_password_file

    # Event listener token.
    # The same one should be configured on Docker registry as Authorization Bearer token.
    event_listener_token: token
    # Retention of records to keep.
    event_retention_days: 7

    # Event listener storage.
    event_database_driver: sqlite3
    event_database_location: data/registry_events.db
    # event_database_driver: mysql
    # event_database_location: user:password@tcp(localhost:3306)/docker_events

    # You can disable event deletion on some hosts when you are running docker-registry on master-master or
    # cluster setup to avoid deadlocks or replication break.
    event_deletion_enabled: True

    # Cache refresh interval in minutes.
    # How long to cache repository list and tag counts.
    cache_refresh_interval: 10

    # If users can delete tags. If set to False, then only admins listed below.
    anyone_can_delete: false
    # Users allowed to delete tags.
    # This should be sent via X-WEBAUTH-USER header from your proxy.
    admins: []

    # Debug mode. Affects only templates.
    debug: true

    # How many days to keep tags but also keep the minimal count provided no matter how old.
    purge_tags_keep_days: 90
    purge_tags_keep_count: 2
    # Enable built-in cron to schedule purging tags in server mode.
    # Empty string disables this feature.
    # Example: '25 54 17 * * *' will run it at 17:54:25 daily.
    # Note, the cron schedule format includes seconds! See https://godoc.org/github.com/robfig/cron
    purge_tags_schedule: ''
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry-ui-data
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: docker-registry
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: docker-registry-ui
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-registry-ui
  namespace: docker-registry
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster
    traefik.ingress.kubernetes.io/frontend-entry-points: https
spec:
  tls:
    - hosts:
        - docker-registry.local
      secretName: docker-registry.local-cert
  rules:
    - host: docker-registry.local
      http:
        paths:
          - path: /ui
            backend:
              serviceName: docker-registry-ui
              servicePort: http
```
