### ISSUE TITLE
force insecure local registry access

### ISSUE THREAD

**Issue by zaherg** [Quiq/registry-ui#76]
Hey there,
First of all, thanks for all the hard work you put into this project.

I noticed that, if you specified the hostname as `xyz.local:5000` it will always assume the protocol as `https`. using the IP address would fix this, but in some environments like mine, the IP is not fixed and changed with every reboot to my cluster.

I can fix that by using the IP address, but I was wondering if there is a way to change that? and specify which protocol to use?

Thanks

**Comment by roman-vynar** [comment]
Thanks!

It does not always assume `https`.
Let's say I set registry.hostname 
```
registry:
  hostname: localhost:5000
```
My local registry is also non-https:
```
version: 0.1

http:
  addr: :5000

storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  delete:
    enabled: true

auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
```

When I start registry-ui but not registry itself (just a test) I get:
```
ERRO[2024-06-23T13:14:05+03:00] [RefreshCatalog] Error fetching catalog: Get "https://localhost:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused; Get "http://localhost:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused  logger=registry.client
```
As you can see at first it tries https, then http which is fine. Finally, when I start registry and then registry-ui no issues using http. 
May be you are talking about insecure verify option when https enabled? E.g. with self-signed certificate.
